SELECT b.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK_SALES a
INNER JOIN BOOK b
ON a.BOOK_ID = b.BOOK_ID
INNER JOIN AUTHOR c
ON b.AUTHOR_ID = c.AUTHOR_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY b.AUTHOR_ID, CATEGORY
ORDER BY b.AUTHOR_ID ASC, CATEGORY DESC;