SELECT ID, IF(CHILD_COUNT IS NULL, 0, CHILD_COUNT) AS CHILD_COUNT
FROM ECOLI_DATA a
LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) as CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) b
ON a.ID = b.PARENT_ID
ORDER BY ID ASC;