SELECT
    a.CAR_ID,
    a.CAR_TYPE,
    FLOOR(a.DAILY_FEE * 30 * (1 - b.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR a
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  b
ON a.CAR_TYPE = b.CAR_TYPE
WHERE
    a.CAR_TYPE IN ('세단', 'SUV') AND
    b.DURATION_TYPE = '30일 이상' AND
    FLOOR(a.DAILY_FEE * 30 * (1 - b.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 2000000 AND
    a.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
    )
ORDER BY FEE DESC, a.CAR_TYPE ASC, a.CAR_ID DESC;