SELECT DISTINCT(a.USER_ID), a.NICKNAME, CONCAT(a.CITY, " ", a.STREET_ADDRESS1, " ", a.STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTRING(a.TLNO, 1, 3), "-", SUBSTRING(a.TLNO, 4, 4), "-", SUBSTRING(a.TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER a
INNER JOIN (SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3 
    ) b
ON a.USER_ID = b.WRITER_ID
ORDER BY USER_ID DESC;