SELECT a.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(SCORE, 2) AS SCORE
FROM REST_INFO a
INNER JOIN (
    SELECT REST_ID, AVG(REVIEW_SCORE) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) b
ON a.REST_ID = b.REST_ID
WHERE ADDRESS LIKE "서울특별시%" OR ADDRESS LIKE "서울시%"
ORDER BY SCORE DESC, FAVORITES DESC;