SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(CONCAT(YEAR(SALES_DATE), MONTH(SALES_DATE), a.USER_ID))) AS USERS
FROM USER_INFO a
INNER JOIN ONLINE_SALE b
ON a.USER_ID = b.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE) ASC, MONTH(SALES_DATE) ASC, GENDER ASC;