WITH RECURSIVE ECOLI_DATA_GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT a.ID, a.PARENT_ID, b.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA a
    JOIN ECOLI_DATA_GENERATION b
    ON a.PARENT_ID = b.ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_DATA_GENERATION
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION ASC
;