SELECT o.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) as TOTAL_SALES
FROM FOOD_ORDER o
INNER JOIN FOOD_PRODUCT p
ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND
    MONTH(PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;