SELECT APNT_NO, PT_NAME, a.PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT a
INNER JOIN PATIENT p
ON a.PT_NO = p.PT_NO
INNER JOIN DOCTOR d
ON a.MDDR_ID = d.DR_ID
WHERE
    DATE(APNT_YMD) = '2022-4-13'
    AND APNT_CNCL_YN = 'N'
    AND a.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC;