SELECT
    a.EMP_NO, 
    EMP_NAME, 
    CASE
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C'
    END AS GRADE,
        CASE
    WHEN AVG(SCORE) >= 96 THEN SAL * 0.2
    WHEN AVG(SCORE) >= 90 THEN SAL * 0.15
    WHEN AVG(SCORE) >= 80 THEN SAL * 0.1
    ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES a
INNER JOIN HR_DEPARTMENT b
ON a.DEPT_ID = b.DEPT_ID
INNER JOIN HR_GRADE c
ON a.EMP_NO = c.EMP_NO
GROUP BY a.EMP_NO
ORDER BY a.EMP_NO ASC;