SELECT ID, GENOTYPE, b.PGENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA a
INNER JOIN (
    SELECT ID AS PID, GENOTYPE AS PGENOTYPE
    FROM ECOLI_DATA
) b
ON a.PARENT_ID = b.PID
WHERE (PGENOTYPE ^ GENOTYPE) + b.PGENOTYPE = GENOTYPE
ORDER BY ID ASC;