SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT SUM(SCORE) AS SCORE, b.EMP_NO AS EMP_NO, EMP_NAME, POSITION, EMAIL
    FROM HR_EMPLOYEES a
    INNER JOIN HR_GRADE b
    ON a.EMP_NO = b.EMP_NO
    WHERE YEAR = 2022
    GROUP BY a.EMP_NO
) a
ORDER BY SCORE DESC
LIMIT 1;