SELECT BOOK.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES
INNER JOIN BOOK
ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
WHERE
    YEAR(SALES_DATE) = 2022 AND
    MONTH(SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;