SELECT
    CASE
        WHEN(GROUP_CONCAT(DISTINCT b.NAME) LIKE '%Python%' AND GROUP_CONCAT(b.CATEGORY) LIKE '%Front End%') THEN 'A'
        WHEN(GROUP_CONCAT(DISTINCT b.NAME) LIKE '%C#%') THEN 'B'
        WHEN(GROUP_CONCAT(DISTINCT b.CATEGORY) LIKE '%Front End%') THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS a
INNER JOIN SKILLCODES b
ON a.SKILL_CODE & b.CODE = b.CODE
GROUP BY ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC
;
